name: CI

on:
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CHROME_BIN: ${{ github.workspace }}/chrome-linux/chrome

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install Chromium
        run: | 
          curl https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F857949%2Fchrome-linux.zip?alt=media -o chrome-linux.zip
          unzip chrome-linux.zip
      - name: Running E2E Tests
        run: |
          npm ci &&
          npm run start &&
          curl --retry 20 --retry-connrefused http://localhost:4200 -I &&
          npm run e2e
